#pragma once

#include "board_common.h"

#define NEXUS_BOARD_IRQ_TABLE(ENTRY) \
    ENTRY(1, "NSWATCHDOG_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(2, "S32KTIMER_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(3, "TIMER0_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(4, "TIMER1_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(5, "DUALTIMER_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(9, "MPC_COMBINED_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(10, "PPC_COMBINED_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(11, "MSC_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(32, "UART0_RX_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(33, "UART0_TX_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(34, "UART1_RX_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(35, "UART1_TX_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(36, "UART2_RX_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(37, "UART2_TX_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(38, "UART3_RX_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(39, "UART3_TX_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(40, "UART4_RX_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(41, "UART4_TX_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(42, "UART0_COMBINED_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(43, "UART1_COMBINED_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(44, "UART2_COMBINED_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(45, "UART3_COMBINED_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(46, "UART4_COMBINED_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(47, "UART_OVERFLOW_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(48, "ETH_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(51, "SPI0_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(52, "SPI1_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(53, "SPI2_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(54, "SPI3_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(55, "SPI4_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(56, "DMA0_ERR_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(57, "DMA0_TC_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(58, "DMA0_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(59, "DMA1_ERR_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(60, "DMA1_TC_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(61, "DMA1_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(62, "DMA2_ERR_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(63, "DMA2_TC_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(64, "DMA2_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(65, "DMA3_ERR_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(66, "DMA3_TC_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(67, "DMA3_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U)

#define NEXUS_BOARD_IRQ_COUNT 42

extern const nexus_irq_desc_t nexus_board_irq_table[NEXUS_BOARD_IRQ_COUNT];
