#pragma once

#include "board_common.h"

#define NEXUS_BOARD_IRQ_TABLE(ENTRY) \
    ENTRY(0, "UART3_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(1, "UART4_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(15, "SPI1_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(23, "I2C1_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(24, "I2C2_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(28, "TIM2_IRQ", NEXUS_IRQ_DOMAIN_NONSECURE, 4U) \
    ENTRY(29, "TIM3_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U) \
    ENTRY(56, "DMA1_Stream0_IRQ", NEXUS_IRQ_DOMAIN_SECURE, 2U)

#define NEXUS_BOARD_IRQ_COUNT 8

extern const nexus_irq_desc_t nexus_board_irq_table[NEXUS_BOARD_IRQ_COUNT];
